# Generated by Django 6.0 on 2026-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_materiaprima_descripcion_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
