# Generated by Django 6.0 on 2026-02-03 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movimientoinventario_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='total_materia_prima_almacenada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='total_producto_almacenado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='item_movido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='responsable_ejecuta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='encargadoinventario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='inventarios',
            field=models.ManyToManyField(blank=True, related_name='movimientos', to='api.inventario'),
        ),
    ]
