# Generated by Django 6.0 on 2026-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movimientoinventario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargadoinventario',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
